[[AMDGPU_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8a11e699ee24eff3b929c05d161cd8e13567e1f"
libc = "glibc"
os = "linux"

    [[AMDGPU_LLVM_Backend.download]]
    sha256 = "32bbcba365bd976c1e594844dbd7b60eb412481341d0335b1fda4f34bb60d161"
    url = "https://github.com/JuliaBinaryWrappers/AMDGPU_LLVM_Backend_jll.jl/releases/download/AMDGPU_LLVM_Backend-v22.1.8+1/AMDGPU_LLVM_Backend.v22.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[AMDGPU_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "862914707bd9427e6d322b85bbfc2c405102e30c"
libc = "glibc"
os = "linux"

    [[AMDGPU_LLVM_Backend.download]]
    sha256 = "8071d8e8c6d1d638497e9098bd74bdb07ca7a78312c782046dfdf32dee324c57"
    url = "https://github.com/JuliaBinaryWrappers/AMDGPU_LLVM_Backend_jll.jl/releases/download/AMDGPU_LLVM_Backend-v22.1.8+1/AMDGPU_LLVM_Backend.v22.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[AMDGPU_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a4c13469dcb6e11230e05cbcf27f87ed99dc6b9"
os = "windows"

    [[AMDGPU_LLVM_Backend.download]]
    sha256 = "d2aa188a95afaea74eb3c56295b15074c3521c11cb81be6c1473cfa3522b856b"
    url = "https://github.com/JuliaBinaryWrappers/AMDGPU_LLVM_Backend_jll.jl/releases/download/AMDGPU_LLVM_Backend-v22.1.8+1/AMDGPU_LLVM_Backend.v22.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
