# Autogenerated wrapper script for AMDGPU_LLVM_Backend_jll for aarch64-linux-gnu-cxx11
export llc, lld

using Zlib_jll
JLLWrappers.@generate_wrapper_header("AMDGPU_LLVM_Backend")
JLLWrappers.@declare_executable_product(llc)
JLLWrappers.@declare_executable_product(lld)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        llc,
        "bin/llc",
    )

    JLLWrappers.@init_executable_product(
        lld,
        "bin/lld",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
