# Autogenerated wrapper script for AMDGPU_LLVM_Backend_jll for x86_64-w64-mingw32-cxx11
export bitcode_path, llc, lld

using Zlib_jll
JLLWrappers.@generate_wrapper_header("AMDGPU_LLVM_Backend")
JLLWrappers.@declare_file_product(bitcode_path)
JLLWrappers.@declare_executable_product(llc)
JLLWrappers.@declare_executable_product(lld)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_file_product(
        bitcode_path,
        "amdgcn\\bitcode",
    )

    JLLWrappers.@init_executable_product(
        llc,
        "bin\\llc.exe",
    )

    JLLWrappers.@init_executable_product(
        lld,
        "bin\\lld.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
