# Autogenerated wrapper script for AMDGPU_LLVM_Backend_jll for x86_64-linux-gnu-cxx11
export bitcode_path, libamdgpu

using Zlib_jll
JLLWrappers.@generate_wrapper_header("AMDGPU_LLVM_Backend")
JLLWrappers.@declare_file_product(bitcode_path)
JLLWrappers.@declare_library_product(libamdgpu, "libamdgpu.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_file_product(
        bitcode_path,
        "amdgcn/bitcode",
    )

    JLLWrappers.@init_library_product(
        libamdgpu,
        "lib/libamdgpu.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
